version: '3.4'

services:
  v-inventory.api:
    image: ${DOCKER_REGISTRY-}vinventoryapi
    build:
      context: .
      dockerfile: V-INVENTORY.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=vinventory;User Id=postgres;Password=postgres;
      - Redis__Configuration=redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: vinventory
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db_data:
